### ISSUE TITLE
JS errors in Safari

### ISSUE THREAD

**Issue by abpei** [SummersideMakerspace/EnigmaMachine#2]
SyntaxError: Unexpected token '='. Expected a ')' or a ',' after a parameter declaration.
(anonymous) enigma.js:20

SyntaxError: Unexpected token '='. Expected a ')' or a ',' after a parameter declaration.
(anonymous) enigma-gui.js:1031

ReferenceError: Can't find variable: EnigmaMachineGUI

**Comment by ghost** [comment]
Safari doesn't support default parameters in function calls. 

So we can't do this;

```
function(pairs = []){
  //do stuff
}
```

Instead we need to do this:

```
function(pairs){
  if(undefined == pairs){
    pairs = [];
  }
  //do stuff
}
```
